### ISSUE TITLE
Handling Cogs

### ISSUE THREAD

**Issue by vinicius507** [agubelu/discord-bot-template#3]
Greetings,
It there any way to make `!commands` command print only commands that are not in cogs?
For example, should I make a Player cog that has commands such as play and pause, is there any way to make it so `!commands` lists commands outside of cogs **and** cogs that exist. I was thinking of building a command for each cog such as `!cog` displays the cog's commands.
Thanks in advance.

**Comment by agubelu** [comment]
Hi, I personally haven't used Cogs in the discord.py library, but it should be possible. According to the [docs](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html#inspection), you can list the commands defined in a Cog by using `Cog.get_commands()`. In this way, maybe you can find a manner to leverage this information in the `Commands` class defined in this template, in order to add the commands defined in a cog to the ones defined in this template.

**Comment by vinicius507** [comment]
I've done it in a bot of mine. Will modify the template and send a PR.
