### ISSUE TITLE
Request for Advice: Non-time based events and conversations

### ISSUE THREAD

**Issue by adibbehjat** [agubelu/discord-bot-template#6]
Hello!

I really liked the way you've set the initial foundation of the discord bot for a great template. I've been expanding the template, but my coding skills when it comes to architecture is weak relative to how you designed this template.

I'd like to ask how would you approach:

### Non-time based events

A great example is `on_member_join`, which relies on a specific discord event. The easiest way is to set it in your_bot.py as:

```python
@client.event
async def on_member_join(member):
   channel = get_channel(client, settings.WELCOME_CHANNEL.lower())
   await channel.send(f"Welcome {member.name}!")
```

However, if we want to introduce additional Discord events, a new line needs to be created which'll create a lot of noise in the your_bot.py file and make it unorganized. How would you organize this form of data?

Since events folder is based only on time based events, can BaseEvent contain a variable to determine what form of event it is (time based or discord event?)

### Conversations

Currently, the Bot relies on commands to conduct a one-way dialog. For two-way, what are some good examples that you're aware of that we can replicate to carry a conversation? Would it be better if this gets managed via DM (to avoid noise from multiple users)?

An example of a conversation is sending a request to the bot as:
```
User A: "Hey @Bot, please create a new announcement!"
Bot: "Sure! Please provide me a...
- Title:
- Message:
- Channel: "
User A: "
- Title: Hi there!
- Message: This is a new message.
- Channel: Announcement"
Bot (in the Announcement Channel): "
Hi There!
This a new message!"
```

Looking forward to your response!

**Comment by agubelu** [comment]
Hi, thanks for your question!

You're right, adding handlers for different Discord events directly in the `your_bot.py` file would make it quite lengthy. In that case I would write a function to register all aditional events, using other auxiliary functions as needed to keep it as short as possible. 

For example, let's suppose that I want to declare the handlers for `on_message` and `on_message_edit` somewhere else. Let's create a `register_handlers.py` file to register those handlers for us:

```py
from handlers.message import common_handle_message

def register_handlers(client):
    @client.event
    async def on_message(message):
        await common_handle_message(client, message)

    @client.event
    async def on_message_edit(before, after):
        await common_handle_message(client, after)
```

You could write the code to handle those events directly there, but then the `register_handlers()` function would be quite long. In that case, we can write more complex functions that deal with the event in question somewhere else, so we just need to call them in the `on_xxx` handlers. 

In this case, I would create a new `handlers/` folder where I can keep all my different handler functions in separate files and import them as needed. For example, `handlers/message.py` would be:

```py
import message_handler
import settings

# The message handler for both new message and edits
async def common_handle_message(client, message):
    text = message.content
    if text.startswith(settings.COMMAND_PREFIX) and text != settings.COMMAND_PREFIX:
        cmd_split = text[len(settings.COMMAND_PREFIX):].split()
        try:
            await message_handler.handle_command(cmd_split[0].lower(), 
                                    cmd_split[1:], message, client)
        except:
            print("Error while handling message", flush=True)
            raise
```
Note that we have to pass the client as an argument as we're no longer in the scope in which it was defined. This way, you can write more complex event handlers in different files, to avoid cluttering any single file with lots of many different event handlers. You'd just need to add the corresponding `@client.event` definition in `register_handlers()` and call that function there.

Of course, we have to register all those handlers in `your_bot.py`, right at the end of the `on_ready` event:

```py
from register_handlers import register_handlers

[...]

@client.event
async def on_ready():
    [...]
    register_handlers(client)
```

This way you won't need to update `your_bot.py` whenever you want to add a new event, just write your handler in the `handlers/` folder and register it as needed in `register_handlers()`.

I'm aware there's probably a nicer way of doing this using [Cogs](https://discordpy.readthedocs.io/en/latest/ext/commands/cogs.html), but I wrote the template at a time when they weren't a thing and it'd require a complete rewrite. They do something similar to what I tried to achieve with this template but it's directly integrated in Discord.py, so you may want to take a look at them.

Regarding your second question, I'm afraid I can't be of much help since I dont have any experience with anything related to conversational bots. I suppose you'd need to persist a certain state between commands, in which case you could use module-level variables or some other persistency method. However, you'll need to modify the template itself, since the message handler ignores all messages that don't start with the command prefix.

**Comment by adibbehjat** [comment]
Thank you for the feedback!

Your insight given the current template is great so far. I'll explore Cogs as well and see what I can find. I'm trying to integrate webhooks to the bot, and I'm noticing that Cogs may be the best solution given a lot of review of examples on Stackoverflow. But the way you described the 'handlers' architecture and modularizing it is very clean and I want to try it out.

Closing issue, and thank you again!
